language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
matrix:
  include:
    - { python: "3.7", dist: xenial, sudo: true }
    - python: 3.5
      env: TOXENV=cov
  allow_failures:
    - env: TOXENV=cov
install:
    - pip install --quiet tox-travis
script:
    - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet coveralls;
      coveralls;
      fi
